version: '3.8'
name: 'wild-workouts'
services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "127.0.0.1:8080:8080"

  trainer-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainer
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      - firestore

  trainer-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainer
    ports:
      - "127.0.0.1:3010:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    depends_on:
      - firestore

  trainings-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainings
    ports:
      - "127.0.0.1:3001:$PORT"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - firestore

  users-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3002:$PORT"
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - firestore

  users-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3020:$PORT"
    environment:
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - firestore

  firestore:
    build:
      context: docker/firestore-emulator
    env_file:
      - .env
    ports:
      - "127.0.0.1:8787:8787"
      - "127.0.0.1:4000:4000"
    restart: unless-stopped

  firestore-component-tests:
    build:
      context: docker/firestore-emulator
    env_file:
      - .env
    ports:
      - "127.0.0.1:8788:8787"
    restart: unless-stopped

  mysql:
    image: mariadb:10
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
